require 'hoe'
require './lib/opmlparser/version.rb'

Hoe.spec 'opmlparser' do

  self.version = OPML::VERSION

  self.summary = "opmlparser - read / parse outlines (incl. feed subscription lists) in the OPML (Outline Processor Markup Language) format in xml"
  self.description = summary

  self.urls    = ['https://github.com/feedreader/pluto']

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = []

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
