require 'hoe'
require './lib/pluto/merge/version.rb'

Hoe.spec 'pluto-merge' do

  self.version = PlutoMerge::VERSION

  self.summary = "pluto-merge - planet site generator (that is, merge 'n' manage planet templates)"
  self.description = summary

  self.urls    = ['https://github.com/feedreader/pluto-merge']

  self.author  = 'Gerald Bauer'
  self.email   = 'feedreader@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'HISTORY.md'

  self.extra_deps = [
    ['pluto-models',  '>= 1.2.2'],
    ['pakman',        '>= 0.5.0'],
    ['fetcher',       '>= 0.4.4'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 1.9.2'
  }

end
