require 'hoe'
require './lib/pluto/news/version.rb'

Hoe.spec 'pluto-news' do

  self.version = PlutoNews::VERSION

  self.summary = "pluto-news - newsreader for easy (re)use - build your own facebook newsfeed in 1-2-3 steps in 5 minutes"
  self.description = summary

  self.urls    = ['https://github.com/feedreader/pluto']

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['pluto-models', '>= 1.6.1'],
    ['pluto-update', '>= 1.6.3'],
    ['sqlite3'],     # note: for easy installation include sqlite database library
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
