require 'hoe'
require './lib/version/check/version.rb'

Hoe.spec 'version-check' do

  self.version = VersionCheck::VERSION

  self.summary = "version-check - up-to-date? - helpers for checking for / reporting outdated gem / library versions"
  self.description = summary

  self.urls    = ['https://github.com/feedreader/pluto']

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'


  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = []

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
